---
title: "Ch_2_code_runs"
author: "Swen Hendrickson"
date: "10/3/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(plotly)
library(sf)
library(tigris) #TIGER database
library(mapview)
library(leaflet)
library(censusapi)

ca_counties <- counties("CA", cb = T, progress_bar = F)
projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

ca_counties_transformed <- 
  ca_counties %>% 
  st_transform(4326) %>% 
  st_transform(26910) %>% 
  st_transform(projection) %>% 
  st_transform(st_crs(ca_counties))

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)
```

```{r MAPPING TECHNIQUES}
# one mapping technique:
ggplot(ca_counties) + geom_sf()

# another mapping technique:
mapview(ca_counties)

# a third, more intricate mapping technique:
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = ca_counties
  ) %>% 
  addMarkers(
    data = ca_counties %>% 
      st_centroid()
  )

# again, but just for the bay
ggplot(bay_counties) + geom_sf()

# use places() to load 'cities'
ca_cities <- places("CA", cb = T, progress_bar = FALSE)

# subset, intersection
bay_cities <- ca_cities[bay_counties,]

# bay cities in map
mapview(bay_counties, alpha.regions = 0) + mapview(bay_cities)

# to leave out cities that just barely touch the counties, map it
bay_cities_within <-
  ca_cities %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_cities %>% select(GEOID)) %>%  # join with field name 'GEOID'
                                              # select(sf_object) auto uses geometry
  st_as_sf()

mapview(bay_counties, alpha.regions = 0) + mapview(bay_cities_within, label = "NAME")

# shorter way to do the stanza performed above
bay_cities_within <-
  ca_cities[which(ca_cities$GEOID %in% st_centroid(ca_cities)[bay_counties, ]$GEOID), ]

mapview(bay_counties, alpha.regions = 0) + mapview(bay_cities_within, label = "NAME")

# to color code and show differences between groups above (touching vs centroids)
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_counties,
    fill = F,
    weight = 2,
    label = ~NAME
  ) %>%
  addPolygons(
    data = bay_cities %>% 
      filter(!GEOID %in% bay_cities_within$GEOID),
    color = "red",
    label = ~NAME
  ) %>% 
  addPolygons(
    data = bay_cities_within,
    color = "green",
    label = ~NAME
  )

# Census Block Groups, aka CBGs (smallest granularity)
bay_cbgs <- block_groups("CA", bay_county_names[1:9], cb = T, progress_bar = F)

# CBGs again, more generalizable looping technique:
bay_cbgs <- 
  bay_county_names %>% 
  map_dfr(function(county) {
    block_groups("CA", county, cb = T, progress_bar = F)
  })
```

```{r ALTERNATE DATA SOURCE FOR GEOMETRIES}
# load (from web URL)
bay_cbgs_clip <- st_read("https://opendata.arcgis.com/datasets/037fc1597b5a4c6994b89c46a8fb4f06_0.geojson")

# map / plot
ggplot(bay_cbgs_clip) + geom_sf()
```

```{r ZCTAs, PGE Data}
usa_zips <- 
  zctas(cb = T, progress_bar = F)

bay_zips <-
  usa_zips %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(usa_zips %>% select(GEOID10)) %>% 
  st_as_sf()

## 
year <- 2020
quarters <- 1:4
type <- "Electric"

pge_20_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "pge/PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_20_elec <- rbind(pge_20_elec,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_20_elec, "pge_20_elec.rds")
}

pge_20_res_elec <-
  pge_20_elec %>% 
  filter(CUSTOMERCLASS == "Elec- Residential") %>% 
  mutate(
    ZIPCODE = ZIPCODE %>% as.character()
  ) %>% 
  group_by(ZIPCODE) %>% 
  summarize(
    TOTALKWH = sum(TOTALKWH, na.rm = T)
  ) %>% 
  right_join(
    bay_zips %>% select(GEOID10),
    by = c("ZIPCODE" = "GEOID10")
  ) %>% 
  st_as_sf() %>% 
  st_transform(4326)

res_pal <- colorNumeric(
  palette = "Reds",
  domain = 
    pge_20_res_elec$TOTALKWH
)

# mapping total kWh by zip code, w nice color pallete to show gradients
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = pge_20_res_elec,
    fillColor = ~res_pal(TOTALKWH),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKWH), 
      " kWh total in ",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = pge_20_res_elec,
    pal = res_pal,
    values = ~TOTALKWH,
    title = "Total Residential<br>kWh, 2020"
  )

# mapping physical health issues in the bay
ca_tracts <- tracts("CA", cb = T, progress_bar = F)

bay_phys_health_18 <- # health_ca not loaded
  health_ca %>% 
  filter(
    Measure == "Physical health not good for >=14 days among adults aged >=18 years",
    Year == 2018
  ) %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("LocationName" = "GEOID")
  ) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("LocationName" = "GEOID")
  ) %>% 
  st_as_sf()

health_pal <- colorNumeric(
  palette = "Purples",
  domain = 
    bay_phys_health_18$Data_Value
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_phys_health_18,
    fillColor = ~health_pal(Data_Value),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(Data_Value), 
      "% in ",
      LocationName
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = bay_phys_health_18,
    pal = health_pal,
    values = ~Data_Value,
    title = "Physical health<br>not good for 14+ days<br>among adults aged<br>18+ years, 2018"
  )
```

# 2.2 ACS Data
```{r ACS DATA}
# default to 5-yr datasets

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

saveRDS(acs_vars_2019_5yr, file = 'acs_vars_2019_5yr.Rdata')

# to get sex by age
smc_sexbyage <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:081",
    vars = "group(B01001)"
  ) %>%
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"sex","age"),
    sep = "!!"
  ) %>% 
  filter(!is.na(age))

# to get % elderly
smc_elderly <- 
  smc_sexbyage %>% 
  mutate(
    elderly = 
      ifelse(
        age %in% c(
          "65 and 66 years",
          "67 to 69 years",
          "70 to 74 years",
          "75 to 79 years",
          "80 to 84 years",
          "85 years and over"
        ),
        estimate,
        NA
      )
  ) %>% 
  group_by(cbg) %>% 
  summarize(
    elderly = sum(elderly, na.rm = T),
    total_pop = sum(estimate, na.rm = T)
  ) %>% 
  mutate(
    percent_elderly = elderly/total_pop*100
  ) %>% 
  filter(!is.na(percent_elderly))

# map using tigris and sf
smc_blockgroups <- block_groups("CA", "San Mateo", cb = T, progress_bar = F)

elderly_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    smc_elderly$percent_elderly
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = 
      smc_elderly %>% 
        left_join(
          smc_blockgroups %>% select(GEOID), 
          by = c("cbg" = "GEOID")
        ) %>% 
        st_as_sf(),
    fillColor = ~elderly_pal (percent_elderly),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(percent_elderly), 
      "% over age 65"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = smc_elderly,
    pal = elderly_pal,
    values = ~percent_elderly,
    title = "% over 65"
  )

```

```{r 2.3 DECENNIAL DATA}

# read in census data, transmutes to just give you block ID# and population
# (this for San Mateo county)
smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )

# below: use 'group' parameter within vars argument
# grabs all categories and sub categories of race within P1 grouping
# also, metadata
dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

smc_pop_race_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

dec_vars_2020 %>% 
  filter(grepl("P1",name)) %>% 
  select(name, label) %>% 
  arrange(name)

# selectively filtering to create 'two or more races' (I think)
smc_pop_race_2020 <- smc_pop_race_2020 %>% 
  mutate(
    race = case_when(
      category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
      category1 == "Population of two or more races:" ~ "",
      !is.na(category2) ~ category2,
      TRUE ~ ""
    )
  )

# remove empty rows, select columns to show, rename 'estimate' col to 'pop'
smc_pop_race_2020 <- smc_pop_race_2020 %>% 
  filter(race != "") %>% 
  select(block, race, pop = estimate)

# to install and use user-developed packages from GitHub
install.packages("devtools")
library(devtools)
install_github('walkerke/tigris')
library(tigris)

# bringing data back in w new packages above
smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

nfo_pop_2020 <- smc_pop_2020 %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

mapview(nfo_pop_2020, zcol = "pop")
```

```{r 2.4 SPATIAL SUBSETS}
# load PDAs (Priority Development Areas)
bay_pdas <- st_read("https://opendata.arcgis.com/datasets/4df9cb38d77346a289252ced4ffa0ca0_0.geojson")

# filter above df for just San Mateo county
smc_pdas <-
  bay_pdas %>% 
  filter(county == "San Mateo") %>% 
  st_transform(4269)

smc_pdas_blocks <- smc_blocks_2020[smc_pdas, ]

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = smc_pdas,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = smc_pdas_blocks,
    color = "red",
    weight = 0.75,
    fill = F
  )

# sum population of red-outlined blocks in SMC (over counts)
smc_pdas_blocks_1 <- smc_pdas_blocks %>% 
  select(block = GEOID20) %>% 
  left_join(smc_pop_2020)

sum(smc_pdas_blocks_1$pop)

# now add just blocks with their centroids w/in PDA boundaries
smc_pdas_blocks_2 <-
  smc_pdas_blocks_1 %>% 
  st_centroid() %>% 
  .[smc_pdas, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_pdas_blocks_1 %>% select(block)) %>% 
  st_as_sf()

sum(smc_pdas_blocks_2$pop)

# map
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = smc_pdas,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = smc_pdas_blocks_2,
    color = "red",
    weight = 0.75,
    fill = F
  )

# prep for cookie cutter procedure
smc_pdas_blocks_area <-
  smc_pdas_blocks %>% 
  st_transform(26910) %>% 
  mutate(area = st_area(.))

# COOKIE CUTTER [st_intersection()]
smc_pdas_blocks_intersection <-
  smc_pdas_blocks_area %>% 
  st_intersection(
    smc_pdas %>% 
      st_transform(26910)
  )

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = smc_pdas,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = smc_pdas_blocks_intersection %>% 
      st_transform(4269),
    color = "red",
    weight = 0.75,
    fill = F
  )

# get leftover area [via st_area()]
smc_pdas_blocks_3 <-
  smc_pdas_blocks %>% 
  select(block = GEOID20) %>% 
  left_join(smc_pop_2020) %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
    smc_pdas %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area,
    pop = pop * perc_area
  )

sum(smc_pdas_blocks_3$pop) %>% round()

# notes:
# 'proportional area adjustment factor' - hold it until the end to multiply pop
# second (centroid) method was pretty accurate 
```

```{r 2.5 MIGRATION}
# tracking income, mobility
# population inflow and outflow

# census meta data
acs_vars_2019_1yr <-
  listCensusMetadata(
    name = "2019/acs/acs1",
    type = "variables"
  )
# load census data B07010 (mobility by income, residence in past 12 mo)
# for only San Mateo County
smc_mobility_current_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:081",
    regionin = "state:06",
    vars = c("group(B07010)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable)

# note: nested structure of data -> AVOID DOUBLE-COUNTING

# distinguish bw 'here since last year' and 'inflow'
# eliminate double counting
smc_mobility_current_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:081",
    regionin = "state:06",
    vars = c("group(B07010)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","temp","income"),
    sep = "!!"
  ) %>% 
  mutate(
    income = ifelse(
      temp == "No income",
      temp,
      income
    ),
    mobility = ifelse(
      mobility %in% c("Same house 1 year ago:", "Moved within same county:"),
      "Here since last year",
      "Inflow"
    )
  ) %>% 
  filter(!is.na(income)) %>% 
  group_by(mobility, income) %>% 
  summarize(estimate = sum(estimate))

# repeat steps for other data B07410 (mobility by income, residence 1 YEAR AGO)
smc_mobility_lastyear_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:081",
    regionin = "state:06",
    vars = c("group(B07410)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable)
# note: fewer labels bc people who left are 'lost'


smc_mobility_lastyear_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:081",
    regionin = "state:06",
    vars = c("group(B07410)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","temp","income"),
    sep = "!!"
  ) %>% 
  mutate(
    income = ifelse(
      temp == "No income",
      temp,
      income
    ),
    mobility = ifelse(
      mobility %in% c("Same house:", "Moved within same county:"),
      "Here since last year",
      "Outflow"
    )
  ) %>% 
  filter(!is.na(income)) %>% 
  group_by(mobility, income) %>% 
  summarize(estimate = sum(estimate))
# here since last year should be the same in both


# get total pop by income tiers (from B07010)
smc_mobility_current_18 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2018,
    region = "county:081",
    regionin = "state:06",
    vars = c("group(B07010)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","temp","income"),
    sep = "!!"
  ) %>% 
  mutate(
    income = ifelse(
      temp == "No income",
      temp,
      income
    ),
    mobility = "Here last year"
  ) %>% 
  filter(!is.na(income)) %>% 
  group_by(mobility, income) %>% 
  summarize(estimate = sum(estimate))

# bind df's, to hold certain counts (here last yr, this yr, outlow, inflow)
# also, PIVOT table to mutate() certain fields for internal and external flows
smc_flows_19 <-
  rbind(
    smc_mobility_current_18,
    smc_mobility_lastyear_19 %>% 
      filter(mobility == "Outflow"),
    smc_mobility_current_19 %>% 
      filter(mobility == "Inflow"),
    smc_mobility_current_19 %>% 
      group_by(income) %>% 
      summarize(estimate = sum(estimate)) %>% 
      mutate(mobility = "Here this year")
  ) %>% 
  pivot_wider(
    names_from = mobility,
    values_from = estimate
  ) %>% 
  mutate(
    `External net` = Inflow - Outflow,
    `Internal net` = `Here this year` - `Here last year` - `External net`,
  ) %>% 
  select(
    `Income tier` = income, 
    `Internal net`,
    `External net`,
    `Here last year`, 
    `Here this year`, 
    Outflow, 
    Inflow
  )

smc_flows_19

# shows that wealthy people moved in, as opposed to locals getting richer
```










